name: build

on:
  pull_request: { }
  workflow_dispatch: {}
  push:
    branches:
      - 'trunk'
    tags-ignore:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        arch: [ amd64 ]
        cmake-arch: [ x86_64 ]
        include:
          - os: macOS-latest
            arch: x86_64
            cmake-arch: x86_64
          - os: macOS-latest
            arch: aarch64
            cmake-arch: arm64
          - os: windows-latest
            arch: x86_64
            cmake-arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 20

      - run: ./gradlew build --stacktrace
        if: matrix.arch == 'amd64' || matrix.arch == 'x86_64'

  publish:
    runs-on: macos-latest
    needs:
      - build

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.13.0
        with:
          distribution: 'zulu'
          java-version: 20

      - run: ./gradlew dokkaHtmlMultiModule

      - run: ./gradlew publish
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'diglol/crypto' }}
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}

      - name: Deploy docs
        if: ${{ github.ref == 'refs/heads/trunk' && github.repository == 'diglol/crypto' }}
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: site
          FOLDER: build/dokka/html
          TARGET_FOLDER: docs/latest/
          CLEAN: true
